pipeline:
  backend-test:
    image: hseeberger/scala-sbt
    commands:
      - cd backend
      - sbt test

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toctoc
