pipeline:
  backend-test:
    image: hseeberger/scala-sbt
    commands:
      - cd backend
      - sbt test
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_SERVER=database
      - DB_NAME=toctoc
  backend-publish:
    image: hseeberger/scala-sbt
    environment:
      - BINTRAY_USER=nemobot
      - BINTRAY_PASS=${BINTRAY_PASSWORD}
    commands:
      - echo $BINTRAY_USER
      - echo $BINTRAY_PASS
      - echo $BINTRAY_PASSWORD
      - cd backend
      - sbt +releaseEarlyPublish
    secrets: [ bintray_password ]
    when:
      event: [ push, tag ]
      status: success


services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toctoc
