clone:
  git:
    image: plugins/git
    tags: true
    recursive: true

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.sbt
    volumes:
      - /tmp/cache:/cache

  backend-test:
    image: hseeberger/scala-sbt
    commands:
      - cd backend
      - sbt test
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_SERVER=database
      - DB_NAME=toctoc

  backend-publish:
    image: hseeberger/scala-sbt
    environment:
      - BINTRAY_USER=nemobot
    commands:
      - cd backend
      - sbt +releaseEarly
    secrets: [ bintray_pass ]
    when:
      event: [ push, tag ]
      status: success

  frontend-test:
    image: node:8
    commands:
      - cd web
      - yarn
      - yarn test

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.sbt
    volumes:
      - /tmp/cache:/cache

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toctoc
