pipeline:
  backend-test:
    image: hseeberger/scala-sbt
    commands:
      - cd backend
      - sbt test
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_SERVER=database
      - DB_NAME=toctoc

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toctoc
