pipeline:
  backend-test:
    image: hseeberger/scala-sbt
    commands:
      - cd backend
      - sbt test
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_SERVER=database
      - DB_NAME=toctoc

  backend-publish:
    image: hseeberger/scala-sbt
    environment:
      - BINTRAY_USER=nemobot
    commands:
      - cd backend
      - sbt +releaseEarly
    secrets: [ bintray_pass ]
    when:
      event: [ push, tag, deployment ]
      status: success

  frontend-test:
    image: node:8
    commands:
      - cd web
      - yarn
      - yarn test

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toctoc
