clone:
  git:
    image: plugins/git
    tags: true
    recursive: true

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.sbt
    volumes:
      - /tmp/cache:/cache

  backend-test:
    group: test
    image: hseeberger/scala-sbt
    commands:
      - cd backend
      - sbt slick/test
      - sbt quill/test
      - sbt slickMySql/test
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_SERVER=database
      - DB_NAME=toctoc
      - MYSQL_DB_URL=jdbc:mysql://MySqlDatabase:3306/toctoc?useSSL=false

  frontend-test:
    group: test
    image: node:8
    commands:
      - cd web
      - yarn
      - yarn test

  backend-publish:
    image: hseeberger/scala-sbt
    environment:
      - BINTRAY_USER=nemobot
    commands:
      - cd backend
      - sbt +releaseEarly
    secrets: [ bintray_pass ]
    when:
      event: [ push, tag ]
      status: success

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.sbt
    volumes:
      - /tmp/cache:/cache

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toctoc
  MySqlDatabase:    
    image: mysql:5.7    
    ports:
      - '3306:3306'
    environment:      
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: toctoc
